### ISSUE TITLE
rake problem

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/ropengov.github.io#17]
Cant build the website. No success fixing this so far. Any help appreciated.

lei@lei-OptiPlex-9020:~/Louhos/ropengov.github.io$ rake site:run_dev
Configuration file: ./_config.yml
_projects
rake aborted!
NoMethodError: undefined method `find_converter_instance' for #<Jekyll::Site:0x00000002e4c828>
/home/lei/Louhos/ropengov.github.io/_plugins/projectlist.rb:34:in `markdownify'
/home/lei/Louhos/ropengov.github.io/_plugins/projectlist.rb:21:in `initialize'
/home/lei/Louhos/ropengov.github.io/_plugins/projectlist.rb:55:in `new'
/home/lei/Louhos/ropengov.github.io/_plugins/projectlist.rb:55:in `block in create'
/home/lei/Louhos/ropengov.github.io/_plugins/projectlist.rb:54:in `each'
/home/lei/Louhos/ropengov.github.io/_plugins/projectlist.rb:54:in `create'
/home/lei/Louhos/ropengov.github.io/_plugins/projectlist.rb:72:in `generate'
/var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:251:in `block in generate'
/var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:250:in `each'
/var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:250:in `generate'
/var/lib/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:45:in `process'
/home/lei/Louhos/ropengov.github.io/Rakefile:108:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => site:run_dev => site:generate
(See full trace by running task with --trace)

**Comment by jlehtoma** [comment]
I'm able to run the current version of the blog. Try running the following command:

```
bundle show
```

Here's my setup:

```
Gems included by the bundle:
  * activesupport (4.2.7)
  * addressable (2.5.1)
  * bundler (1.14.6)
  * coffee-script (2.4.1)
  * coffee-script-source (1.12.2)
  * colorator (1.1.0)
  * concurrent-ruby (1.0.5)
  * ethon (0.10.1)
  * execjs (2.7.0)
  * extras (0.1.0)
  * faraday (0.12.0.1)
  * fastimage (2.1.0)
  * ffi (1.9.18)
  * forwardable-extended (2.6.0)
  * gemoji (3.0.0)
  * github-pages (134)
  * github-pages-health-check (1.3.3)
  * html-pipeline (2.5.0)
  * i18n (0.8.1)
  * jekyll (3.4.3)
  * jekyll-assets (2.2.8)
  * jekyll-avatar (0.4.2)
  * jekyll-coffeescript (1.0.1)
  * jekyll-default-layout (0.1.4)
  * jekyll-feed (0.9.2)
  * jekyll-gist (1.4.0)
  * jekyll-github-metadata (2.3.1)
  * jekyll-mentions (1.2.0)
  * jekyll-optional-front-matter (0.1.2)
  * jekyll-paginate (1.1.0)
  * jekyll-readme-index (0.1.0)
  * jekyll-redirect-from (0.12.1)
  * jekyll-relative-links (0.4.0)
  * jekyll-sass-converter (1.5.0)
  * jekyll-seo-tag (2.2.0)
  * jekyll-sitemap (1.0.0)
  * jekyll-swiss (0.4.0)
  * jekyll-theme-architect (0.0.4)
  * jekyll-theme-cayman (0.0.4)
  * jekyll-theme-dinky (0.0.4)
  * jekyll-theme-hacker (0.0.4)
  * jekyll-theme-leap-day (0.0.4)
  * jekyll-theme-merlot (0.0.4)
  * jekyll-theme-midnight (0.0.4)
  * jekyll-theme-minimal (0.0.4)
  * jekyll-theme-modernist (0.0.4)
  * jekyll-theme-primer (0.1.8)
  * jekyll-theme-slate (0.0.4)
  * jekyll-theme-tactile (0.0.4)
  * jekyll-theme-time-machine (0.0.4)
  * jekyll-titles-from-headings (0.1.5)
  * jekyll-watch (1.5.0)
  * jemoji (0.8.0)
  * json (1.8.6)
  * kramdown (1.13.2)
  * libv8 (3.16.14.19)
  * liquid (3.0.6)
  * listen (3.0.6)
  * maruku (0.7.3)
  * mercenary (0.3.6)
  * mini_portile2 (2.1.0)
  * minima (2.0.0)
  * minitest (5.10.1)
  * multi_json (1.12.1)
  * multipart-post (2.0.0)
  * net-dns (0.8.0)
  * nokogiri (1.7.1)
  * octokit (4.7.0)
  * pathutil (0.14.0)
  * public_suffix (2.0.5)
  * pygments.rb (1.1.2)
  * rack (1.6.5)
  * rake (12.0.0)
  * rb-fsevent (0.9.8)
  * rb-inotify (0.9.8)
  * ref (2.0.0)
  * rouge (1.11.1)
  * rubyzip (1.2.1)
  * safe_yaml (1.0.4)
  * sass (3.4.23)
  * sawyer (0.8.1)
  * sprockets (3.6.3)
  * table_print (1.5.6)
  * terminal-table (1.7.3)
  * therubyracer (0.12.3)
  * thread_safe (0.3.6)
  * typhoeus (0.8.0)
  * tzinfo (1.2.3)
  * uglifier (3.2.0)
  * unicode-display_width (1.1.3)
```

My ruby version is:

```
ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux-gnu]
```

Note that sometime removing `Gemfile.lock` file and re-running `bundle install` helps.

**Comment by antagomir** [comment]
Thanks this helped. 

However after generating the new eurostat blog post with knitpost.R and running rake site dev or rake publish, the new blog post seems to appear on front page but without a title: http://ropengov.github.io/ - I tried to compare the Rmd file to others but no apparent solutions there. Could this be related to jekyll updates ?

**Comment by jlehtoma** [comment]
After pulling the latest changes and running `rake site:run_dev`, I get the following on localhost:

![ropengov_blog](https://cloud.githubusercontent.com/assets/525495/25119901/4bf89b56-241c-11e7-9b20-ed3a595f6069.png)

The eurostat post is there, but so is another ghost post with only "WRITTEN BY - APRIL 18, 2017". This seems to be the current date. However, I don't see the eurostat post in https://ropengov.github.io/

This might indeed have something to do with new versions of Jekyll. The code that is generating the frontpage listing lives in [`index.html`](https://github.com/rOpenGov/ropengov.github.io/blob/master/index.html), more specifically this part

```
<article class="container">
{% for post in paginator.posts %}
  {% unless post.draft %}
    <section class="index">
        <!-- {% if post.author.image %}<img src="/images/{{ post.author.image }}" class="avatar">{% endif %}-->
        <div>
            <h2 class="title"><a href="{{ post.url }}" rel="prefetch">{{ post.title }}</a></h2>
            <p>{{ post.excerpt }}</p>
            <div class="meta">
                Written By <address>{{ post.author.name }}</address> &mdash;
                <time pubdate datetime="{{ post.date | date: "%Y-%d-%B" }}" title="{{ post.date | date: "%B %d, %Y" }}">{{ post.date | date: "%B %d, %Y" }}</time>
            </div>
        </div>
        <hr>
    </section>
    {% endunless %}
    {% endfor %}
    <section class="pagination" style="text-align:center">
      {% if paginator.previous_page %}
        {% if paginator.previous_page == 1 %}
        <a href="/" class="btn btn-outline">‹ Newer</a>
        {% else %}
        <a href="/page{{ paginator.previous_page }}" class="btn btn-outline">‹ Newer</a>
        {% endif %}
      {% endif %}
      {% if paginator.next_page %}
        <a href="/page{{ paginator.next_page }}" class="btn btn-outline">Older ›</a>
      {% endif %}
    </section>
</article>
```

Unfortunately I have no time to investigate this further right now.

**Comment by antagomir** [comment]
Thanks a lot for having a look. I updated the site and at least the new blog post is visible now. Let's hope that we can find time to sort this out in the future.
